regCompact <- read.csv("regular_season_compact_results.csv")
regResult <- read.csv("regular_season_detailed_results.csv")
seasons <- read.csv("seasons.csv")
teams <- read.csv("teams.csv")
tCompact <- read.csv("tourney_compact_results.csv")
tDetail <- read.csv("tourney_detailed_results.csv")
tSeed <- read.csv("tourney_seeds.csv")
tSlot <- read.csv("tourney_slots.csv")

sampleSub <- read.csv("sample_submission.csv")